@startuml

left to right direction
skinparam packageStyle rectangle

actor Відвідувач
actor Користувач
actor Власник
actor Адміністратор

rectangle "Система управління даними" {
  (Відвідувач) -- (View all datasets)
  (Відвідувач) -- (Registration)
  (Користувач) .> (Відвідувач) : <<extends>>
  (Власник) .> (Користувач) : <<extends>>
  (Адміністратор) .> (Власник) : <<extends>>
  (Користувач) -- (View Additional Information)
  (Користувач) -- (Download Dataset)
  (Користувач) -- (Login)
  (Власник) -- (Dataset Management)
  (Dataset Management) -- (Create Dataset)
  (Dataset Management) -- (Delete Dataset)
  (Dataset Management) -- (Edit Dataset)
  (Dataset Management) -- (Achive Dataset)
  (Адміністратор) -- (User Management)
  (User Management) -- (Delete User)
  (User Management) -- (View all users)
}

@enduml